name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: bookstore
          POSTGRES_USER: bookstore_user
          POSTGRES_PASSWORD: strongpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U bookstore_user -d bookstore"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://bookstore_user:strongpassword@localhost:5432/bookstore
      DEBUG: 0
      SECRET_KEY: test-secret-key
      ALLOWED_HOSTS: localhost,127.0.0.1

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate --noinput
        working-directory: ./ecommerce

      - name: Run tests
        run: |
          python manage.py test
        working-directory: ./ecommerce
