name: Django CI

on: [push, pull_request]

## jobs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

          ## dependencies 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./ecommerce   

      - name: Run migrations
        run: |
          python manage.py migrate --noinput
        working-directory: ./ecommerce   

      - name: Run tests
        run: |
          python manage.py test
        working-directory: ./ecommerce   
