name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ecommerce     
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt   # go one level up to root for requirements.txt

      - name: Run Tests
        working-directory: ecommerce
        run: |
          python manage.py test
